kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc1
provisioner: kubernetes.io/aws-ebs
parameters:
 type: gp2
 fsType: ext4
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate